[build]
  environment = { HUGO_VERSION = "0.55.6" }
  command = "hugo"
  publish = "public"

[[redirects]]
  from = "/rsaparty"
  to = "https://fleet-launch-party-at-rsac.eventbrite.com/?aff=bsides"

[[redirects]]
  from = "/*"
  to = "https://calendly.com/zwass/:splat"
